# On mac, run the following command in the terminal to symlink and generate a languages.toml
# ln -s languages.mac.toml languages.toml

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/Users/bhargavaman/Library/pnpm/global/5/node_modules/typescript/lib" }, environment = "node" }

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]
